apiVersion: v1
kind: Secret
metadata:
  name: graphdb-dev-tls
  namespace: wifire-kg
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: graphdb-prod-tls
  namespace: wifire-kg
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key> 