apiVersion: v1
kind: Secret
metadata:
  name: langgraph-secrets
  namespace: wifire-kg
  labels:
    app: langgraph
type: Opaque
data:
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  LANGSMITH_API_KEY: ${LANGSMITH_API_KEY}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_S3_ENDPOINT_URL: aHR0cHM6Ly9zMy13ZXN0Lm5ycC1uYXV0aWx1cy5pbw==
  AWS_S3_BUCKET_NAME: d2lsZGZpcmUta2c=
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
  GRAPHDB_URL: ${GRAPHDB_URL}
  GRAPHDB_REPOSITORY: ${GRAPHDB_REPOSITORY}
  GRAPHDB_USERNAME: ${GRAPHDB_USERNAME}
  GRAPHDB_PASSWORD: ${GRAPHDB_PASSWORD}
  TAVILY_API_KEY: ${TAVILY_API_KEY}
  DEBUG: ${DEBUG}
  LOG_LEVEL: ${LOG_LEVEL}
  LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
  LANGCHAIN_TRACING_V2: ${LANGCHAIN_TRACING_V2}