apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
  namespace: wifire-kg
  labels:
    app: supabase
type: Opaque
data:
  POSTGRES_PASSWORD: ${SUPABASE_POSTGRES_PASSWORD}
  JWT_SECRET: ${SUPABASE_JWT_SECRET}
  ANON_KEY: ${SUPABASE_ANON_KEY}
  SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY} 